- app/assets/stylesheets/application.css
- app/views/sidebar/_search.html.haml
#19 and #59 should be addressed here. I was able to test on an actual phone (but not all phones) and so far it's working. When focus turns to an input, it no longer auto zooms. Also, the autofocus has been dropped for search to avoid the keyboard coming up when you first drop into the mobile site.
Can anyone on @sfbrigade/core-website-tools take a look and see if this appears ready for merge?
> Fix mobile issues related to form inputs

- .travis.yml
- test/controllers/main_controller_test.rb
Allows us to only deploy code where the tests are passing. I personally think
this is better, but am curious if there are any other opinions.
We could remove the direct Github -> Heroku integration after this is merged.
> Deploy to Heroku from TravisCI

- app/views/layouts/application.html.haml
- app/views/users/thank_you.html.haml
- config/locales/en.yml
Opening this to get initial feedback on #11
So far it looks something like: 
@hackajesse I'll still need some copy (currently it just defaults to `I just adopted a drain!` for the body of the e-mail and tweet. Facebook only allows you to prepopulate the URL. Were there any other services you think would be good to include?
> Initial implementation of share buttons

- app/assets/javascripts/main.js.erb
- app/views/passwords/edit.html.haml
- app/views/sidebar/_combo_form.html.haml
- app/views/sidebar/_search.html.haml
- app/views/sidebar/edit_profile.html.haml
- app/views/things/adopt.html.haml
Needed to update the CSS class for errors to be `has-error` and mark all
of the labels associated with inputs with the class `control-label` to
have the newer Bootstrap CSS mark the fields correctly.
Addresses #58
> Fix displaying of form errors

- app/views/sidebar/_combo_form.html.haml
Addresses #56 
The fields aren't required, so simplest route is to just hide them.
> Hide phone number fields

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/reminders_controller.rb
- app/helpers/users_helper.rb
- app/views/users/profile.html.haml
- test/controllers/reminders_controller_test.rb
- test/fixtures/users.yml
Only show the button if they are an admin and protect the reminder
endpoint.
Also include byebug for runtime inspection while debugging.
Addresses #79
> Only allow admins to send reminders

- app/views/sidebar/_combo_form.html.haml
- config/locales/en.yml
PUC would like to still ask for mobile phone as an optional field. I reintroduced it and then updated the labeling convention. There was some cognitive switching between the lock icon (meaning private) and the text labels. Folks consistently were thinking all of the things marked private were required. 
I've just simplified to text labels, labeling the optional fields optional. Research suggests users are more likely to fill out the optional fields this way instead of marking all the required fields.
> Add back mobile option, update labels for consistency

- config/locales/en.yml
Addresses #89 
Facebook sharer doesn't allow default text, so that copy is not included.
> Update social media copy

- app/assets/javascripts/main.js.erb
> Add alt text to icons in legend

- Gemfile
- Gemfile.lock
A simple addition that makes developing off of Windows possible.
Based off of this article: https://github.com/tzinfo/tzinfo/wiki/Resolving-TZInfo::DataSourceNotFound-Errors
> Added the tzinfo gem for Windows support

- app/assets/javascripts/main.js.erb
Otherwise they don't dismiss correctly. Using `.data()` doesn't set the
attribute, which it appears is required by bootstrap.
Fixes #163
> Make sure the data dismiss attribute is set on dynamically injected alerts

- app/views/users/thank_you.html.haml
Rather than redirect the page the user is on
Fixes #181
> Update social media links to open new tab

- app/controllers/reminders_controller.rb
- app/controllers/things_controller.rb
The old `#deliver` method is deprecated.
Using new Rails 5 `#deliver_later` instead.
> Fix Mailer Deprecations

- app/assets/javascripts/main.js.erb
- app/assets/stylesheets/screen.css
- app/views/main/index.html.haml
- app/views/passwords/_edit.html.haml
- app/views/sidebar/_combo_form.html.haml
- app/views/sidebar/_search.html.haml
- app/views/sidebar/_user_things.html.haml
- app/views/sidebar/edit_profile.html.haml
- config/locales/en.yml
- test/controllers/main_controller_test.rb
This will help users discover adoptable drains in their area before
signing up.
This moves user registration / log-in from displaying immediately to
requiring the user to click a button to avoid making the sidebar so
busy.
Addresses #103
> Allow the user to search before signing in

- app/assets/stylesheets/application.css
- app/views/main/index.html.haml
- app/views/main/unauthenticated.html.haml
- config/locales/en.yml
- test/controllers/main_controller_test.rb
Change from alert message to traditional button to get highlight and
rounded corner behavior. Also remove "Click here..." text.
Added word-wrap since the default bootstrap behavior is to not wrap text
for buttons, but we need this for buttons like this with longer text.
Fixes #252
> Make program background button behave more like a normal button

- app/assets/javascripts/main.js.erb
- app/controllers/things_controller.rb
- app/models/thing.rb
- app/views/sidebar/_user_things.html.haml
- app/views/things/_abandon.html.haml
- app/views/things/adopt.html.haml
- app/views/users/profile.html.haml
- db/migrate/20170926173203_add_adopted_name_to_things.rb
- db/schema.rb
- lib/thing_importer.rb
- test/controllers/things_controller_test.rb
- test/lib/thing_importer_test.rb
- test/models/thing_test.rb
Rather than overwriting the `name` field which is the canonical name of
the thing, store the adopted name separately. This simplifies the import
logic and also allows the displayed drain name to revert back to the
canonical name when a drain is abandoned.
> Move user adoption name to separate field

- .rubocop.yml
- lib/adoption_mover.rb
- lib/tasks/data.rake
- test/lib/adopted_mover_test.rb
Occasionally adoptions are deleted when invalid data is corrected within
the source and reimported. This task will automatically move adoptions
that were close to other, unadopted, things as it is likely that the
unadopted thing is actually the one that the user adopted.
> Add rake task for migrating deleted adoptions

- app/models/thing.rb
- db/migrate/20180123031630_enable_earth_distance_extension.rb
- db/schema.rb
- lib/adoption_mover.rb
More readible and solves the issues we had where the query lat/lng
resulting in a value outside of [1,-1] within ACOS() leading to an
error, "input is out of range". This appears to occur when the lat/lng
in the query exactly matches a thing's location. E.g.
```
SELECT
ACOS(
COS(RADIANS(37.7876114900295))
* COS(RADIANS(37.78761149002950))
* COS(RADIANS(-122.39915856367400) - RADIANS(-122.399158563674))
+ SIN(RADIANS(37.7876114900295))
* SIN(RADIANS(37.78761149002950))
)
;
```
Results in `ERROR:  input is out of range`.
I _think_ this is because of floating point imprecision because if we
remove the ACOS:
```
SELECT
COS(RADIANS(37.7876114900295))
* COS(RADIANS(37.78761149002950))
* COS(RADIANS(-122.39915856367400) - RADIANS(-122.399158563674))
+ SIN(RADIANS(37.7876114900295))
* …
```
> Switch from Haversine formula to earth_distance Postgres extension

- app/views/sidebar/edit_profile.html.haml
- app/views/users/profile.html.haml
- test/controllers/info_window_controller_test.rb
To match the labeling on the user registration form as this is the
labeling people are most likely to have seen. Update the user profile
edit form to match this as labeling.
> Hide user last name from adopted drain info box

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/controllers/passwords_controller.rb
- app/controllers/users_controller.rb
- app/helpers/application_helper.rb
- app/models/user.rb
- config/initializers/rails_admin.rb
- db/migrate/00000000000002_add_devise_to_users.rb
- db/migrate/20160326200455_user_split_name.rb
- db/migrate/20180509181541_add_priority_to_thing.rb
- lib/adoption_mover.rb
- lib/thing_importer.rb
https://github.com/sfbrigade/adopt-a-drain/pull/408 caused a development/testing regression since [updating Rubocop to 0.72.0 removed Rails linting support](https://github.com/rubocop-hq/rubocop/issues/5976).
Add the [`rubocop-rails` gem](https://github.com/rubocop-hq/rubocop-rails) to restore missing Rails cops.
I made the following improvements while I had the Rubocop context:
- Bumped to latest Rubocop version (`0.72.0` → `0.73.0`)
- Set target Rails version to `5.2` (from `4.0`)
- Disable cops at specific violations (instead of disabling for entire file)
---
Also, I just adopted my first drain today! 💜❤️🧡💛💚💙
> Rubocop Rails Fix
