lib/tasks/data.rake
=> double-quotes vs single-quotes

app/assets/javascripts/main.js.erb, app/assets/stylesheets/application.css, app/controllers/info_window_controller.rb
=> Fix info window not returning thank you on adoption

app/assets/stylesheets/application.css, app/assets/stylesheets/screen.css, app/views/main/index.html.haml, app/views/sidebar/_guidelines.html.haml, app/views/sidebar/_tos.html.haml, config/locales/en.yml, test/controllers/main_controller_test.rb
To address #65  
I've kept this simple and just used the content from the email. I did a rough draft of a different intro, but I'll want Jean to review that.
I'm sure we could make this more exciting and colorful, but we can do that for a future round.
=> Add modal guidelines and connect to tagline as link

app/mailers/application_mailer.rb, app/views/thing_mailer/first_adoption_confirmation.text.erb, test/mailers/thing_mailer_test.rb
=> Update first adoption email content, change from address

app/mailers/thing_mailer.rb, app/views/users/profile.html.haml, config/locales/en.yml, test/controllers/info_window_controller_test.rb, test/controllers/reminders_controller_test.rb, test/fixtures/things.yml
=> Pass through thing default name when drain name is blank

app/views/sidebar/_guidelines.html.haml
=> Update guidelines language

config/locales/en.yml
I think I must have overwritten my earlier changes by accident. This should take care of it.
=> Fix social language

app/controllers/things_controller.rb, app/views/thing_mailer/first_adoption_confirmation.text.erb, app/views/thing_mailer/second_adoption_confirmation.text.erb, test/controllers/things_controller_test.rb
Addresses #104 and makes some minor copy changes to the first and second email.
=> Remove third email on adoption, minor changes to email copy

app/helpers/users_helper.rb, app/views/users/profile.html.haml
Decided to not let admins do this either
Fixes #105
=> Remove button to remind users from modal

app/views/users/sign_in.html.haml, config/locales/en.yml, test/controllers/info_window_controller_test.rb
=> Add link to learn more about adopting a drain to unauthenticated adopt modal

app/models/thing.rb, config/application.rb, db/migrate/20160111062953_add_system_use_code_to_things.rb, db/schema.rb, lib/tasks/data.rake
And populate via the data:load_drains rake task. Refactor the rake task to
update fields using the unique city_id identifier if the drain already
exists.
Require rake in the tasks file so that the environment is loaded properly.
Fixes #100
=> Add system use code to things

config/locales/en.yml
To most current copy
Fixes #89
=> Update social media sharing copy

app/views/thing_mailer/first_adoption_confirmation.text.erb
To bring it inline with current revisions.
Addresses #90
=> Update e-mail copy for first e-mail

config/environments/production.rb, config/initializers/devise.rb
Current domains are invalid, update to real ones
Partially applicable to #93
=> Update default mail host and devise email mailer

app/assets/javascripts/main.js.erb
as this is redundant
Fixes #127
=> Strip `Available -` from legend

app/views/main/index.html.haml
=> Update feedback e-mail to info@sfwater.org

app/assets/stylesheets/application.css, app/views/main/index.html.haml
Not sure why these were hidden, but it seems like a good idea to always
have the visible.
Fixes #117
=> Show guidelines when logged in

app/views/sidebar/_search.html.haml
=> Bump number of drains loaded per map action to 25

app/views/thing_mailer/first_adoption_confirmation.text.erb
=> Update email copy to latest

app/assets/javascripts/main.js.erb
Feels weird that it isn't allowed
=> Enable the scroll wheel for zooming

app/views/sidebar/_guidelines.html.haml
Also remove superfluous whitespace
Addresses #65
=> Add disclamier to guidelines

app/assets/javascripts/main.js.erb
Was not binding to the form to process it correctly and instead allowing
it to submit.
Addresses #149
=> Fix error with binding of edit form

app/assets/stylesheets/application.css, app/views/sidebar/_search.html.haml
To match closer to the label on the form element.
Addresses #88
=> Update styling of header of "my things" list

app/views/main/index.html.haml, config/locales/en.yml
=> Add alpha banner to encourage feedback

app/assets/javascripts/main.js.erb
Show a friendly error message (that the link is invalid)
Fixes #162
=> Update error text for invalid password tokens

app/controllers/application_controller.rb
=> Redirect to HTTPS in production

config/initializers/rails_admin.rb
=> Change thing name in rails admin

config/locales/en.yml
No longer temporarally relevant
Fixes #180
=> Remove references to El Nino

app/views/thing_mailer/second_adoption_confirmation.html.erb
=> Fix link for Adopt-a-Street in adoption email

Gemfile, Gemfile.lock, app/models/thing.rb
removes a bunch of obsolete, outdated, and/or unneeded dependencies
=> Gemfile Cull

app/views/main/index.html.haml, app/views/sidebar/_background.html.haml, config/locales/en.yml
And add link to header and footer
Fixes #190
=> Add content about the project background

app/models/thing.rb, app/views/main/index.html.haml, app/views/sidebar/_search.html.haml, config/locales/en.yml, test/models/thing_test.rb
=> Add number of adopted drains to sidebar

app/assets/javascripts/main.js.erb, app/models/user.rb, app/views/sidebar/_combo_form.html.haml, test/controllers/users_controller_test.rb, test/models/user_test.rb
Grandfather in existing users without a last name.
=> Make last name a required field for new users

app/views/sidebar/_background.html.haml, app/views/sidebar/_guidelines.html.haml, config/environments/development.rb
=> Have links open new window 212

config/initializers/rails_admin.rb
=> Added a label MaximoID for Admin interface City field

app/assets/javascripts/constants.js.erb, app/assets/javascripts/main.js.erb
This should allow us to rename `main.js.erb` to `main.js` in the future.
=> Move JavaScript constants into their own file

app/assets/stylesheets/application.css
Rather than a static height to avoid empty space
Adjustment to #237
Fixes #234
=> Set the max-height of the adopted drain list

app/views/main/index.html.haml
=> Update SFWater logo to link to Adopt-a-Drain page

app/views/thing_mailer/first_adoption_confirmation.html.erb, app/views/thing_mailer/second_adoption_confirmation.html.erb
=> Update formating of drain e-mails to match #254

README.md
=> Fix broken README link for branching

README.md
instructions said `load_drains`, code expects `load_things`
=> Correct db rake step instruction

app/assets/javascripts/main.js.erb
=> Remove additional Google Maps POIs

app.json, config/initializers/geokit.rb
This now requires a key for all usage (not just high usage)
=> Configure Google Geocoder API

lib/thing_importer.rb, test/lib/thing_importer_test.rb
The format seems to have changed from (lat,lng) to POINT(lng, lat)
=> Update location parsing during import
